// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateTechAdGroupHandlerFunc turns a function with the right signature into a create tech ad group handler
type CreateTechAdGroupHandlerFunc func(CreateTechAdGroupParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateTechAdGroupHandlerFunc) Handle(params CreateTechAdGroupParams) middleware.Responder {
	return fn(params)
}

// CreateTechAdGroupHandler interface for that can handle valid create tech ad group params
type CreateTechAdGroupHandler interface {
	Handle(CreateTechAdGroupParams) middleware.Responder
}

// NewCreateTechAdGroup creates a new http.Handler for the create tech ad group operation
func NewCreateTechAdGroup(ctx *middleware.Context, handler CreateTechAdGroupHandler) *CreateTechAdGroup {
	return &CreateTechAdGroup{Context: ctx, Handler: handler}
}

/*CreateTechAdGroup swagger:route POST /adgroup/tech createTechAdGroup

CreateTechAdGroup create tech ad group API

*/
type CreateTechAdGroup struct {
	Context *middleware.Context
	Handler CreateTechAdGroupHandler
}

func (o *CreateTechAdGroup) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateTechAdGroupParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
