// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateFoldersHandlerFunc turns a function with the right signature into a create folders handler
type CreateFoldersHandlerFunc func(CreateFoldersParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateFoldersHandlerFunc) Handle(params CreateFoldersParams) middleware.Responder {
	return fn(params)
}

// CreateFoldersHandler interface for that can handle valid create folders params
type CreateFoldersHandler interface {
	Handle(CreateFoldersParams) middleware.Responder
}

// NewCreateFolders creates a new http.Handler for the create folders operation
func NewCreateFolders(ctx *middleware.Context, handler CreateFoldersHandler) *CreateFolders {
	return &CreateFolders{Context: ctx, Handler: handler}
}

/*CreateFolders swagger:route POST /folders createFolders

CreateFolders create folders API

*/
type CreateFolders struct {
	Context *middleware.Context
	Handler CreateFoldersHandler
}

func (o *CreateFolders) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateFoldersParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
