// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/jobdoner/vtm-refactor/models"
)

// CreateCampaignOKCode is the HTTP code returned for type CreateCampaignOK
const CreateCampaignOKCode int = 200

/*CreateCampaignOK create campaign

swagger:response createCampaignOK
*/
type CreateCampaignOK struct {

	/*
	  In: Body
	*/
	Payload *models.CreateCampaignResp `json:"body,omitempty"`
}

// NewCreateCampaignOK creates CreateCampaignOK with default headers values
func NewCreateCampaignOK() *CreateCampaignOK {

	return &CreateCampaignOK{}
}

// WithPayload adds the payload to the create campaign o k response
func (o *CreateCampaignOK) WithPayload(payload *models.CreateCampaignResp) *CreateCampaignOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create campaign o k response
func (o *CreateCampaignOK) SetPayload(payload *models.CreateCampaignResp) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateCampaignOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateCampaignConflictCode is the HTTP code returned for type CreateCampaignConflict
const CreateCampaignConflictCode int = 409

/*CreateCampaignConflict Campaign already exist

swagger:response createCampaignConflict
*/
type CreateCampaignConflict struct {
}

// NewCreateCampaignConflict creates CreateCampaignConflict with default headers values
func NewCreateCampaignConflict() *CreateCampaignConflict {

	return &CreateCampaignConflict{}
}

// WriteResponse to the client
func (o *CreateCampaignConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}

// CreateCampaignInternalServerErrorCode is the HTTP code returned for type CreateCampaignInternalServerError
const CreateCampaignInternalServerErrorCode int = 500

/*CreateCampaignInternalServerError Internal Server Error

swagger:response createCampaignInternalServerError
*/
type CreateCampaignInternalServerError struct {
}

// NewCreateCampaignInternalServerError creates CreateCampaignInternalServerError with default headers values
func NewCreateCampaignInternalServerError() *CreateCampaignInternalServerError {

	return &CreateCampaignInternalServerError{}
}

// WriteResponse to the client
func (o *CreateCampaignInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
