// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateCampaignHandlerFunc turns a function with the right signature into a create campaign handler
type CreateCampaignHandlerFunc func(CreateCampaignParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateCampaignHandlerFunc) Handle(params CreateCampaignParams) middleware.Responder {
	return fn(params)
}

// CreateCampaignHandler interface for that can handle valid create campaign params
type CreateCampaignHandler interface {
	Handle(CreateCampaignParams) middleware.Responder
}

// NewCreateCampaign creates a new http.Handler for the create campaign operation
func NewCreateCampaign(ctx *middleware.Context, handler CreateCampaignHandler) *CreateCampaign {
	return &CreateCampaign{Context: ctx, Handler: handler}
}

/*CreateCampaign swagger:route POST /campaign createCampaign

CreateCampaign create campaign API

*/
type CreateCampaign struct {
	Context *middleware.Context
	Handler CreateCampaignHandler
}

func (o *CreateCampaign) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateCampaignParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
