// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/jobdoner/vtm-refactor/models"
)

// CreateFoldersCreatedCode is the HTTP code returned for type CreateFoldersCreated
const CreateFoldersCreatedCode int = 201

/*CreateFoldersCreated create folder

swagger:response createFoldersCreated
*/
type CreateFoldersCreated struct {

	/*
	  In: Body
	*/
	Payload *models.CreateFolderResp `json:"body,omitempty"`
}

// NewCreateFoldersCreated creates CreateFoldersCreated with default headers values
func NewCreateFoldersCreated() *CreateFoldersCreated {

	return &CreateFoldersCreated{}
}

// WithPayload adds the payload to the create folders created response
func (o *CreateFoldersCreated) WithPayload(payload *models.CreateFolderResp) *CreateFoldersCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create folders created response
func (o *CreateFoldersCreated) SetPayload(payload *models.CreateFolderResp) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateFoldersCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateFoldersConflictCode is the HTTP code returned for type CreateFoldersConflict
const CreateFoldersConflictCode int = 409

/*CreateFoldersConflict Folder already exist

swagger:response createFoldersConflict
*/
type CreateFoldersConflict struct {
}

// NewCreateFoldersConflict creates CreateFoldersConflict with default headers values
func NewCreateFoldersConflict() *CreateFoldersConflict {

	return &CreateFoldersConflict{}
}

// WriteResponse to the client
func (o *CreateFoldersConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}

// CreateFoldersInternalServerErrorCode is the HTTP code returned for type CreateFoldersInternalServerError
const CreateFoldersInternalServerErrorCode int = 500

/*CreateFoldersInternalServerError Internal Server Error

swagger:response createFoldersInternalServerError
*/
type CreateFoldersInternalServerError struct {
}

// NewCreateFoldersInternalServerError creates CreateFoldersInternalServerError with default headers values
func NewCreateFoldersInternalServerError() *CreateFoldersInternalServerError {

	return &CreateFoldersInternalServerError{}
}

// WriteResponse to the client
func (o *CreateFoldersInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
