// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/jobdoner/vtm-refactor/models"
)

// CreateAdOKCode is the HTTP code returned for type CreateAdOK
const CreateAdOKCode int = 200

/*CreateAdOK create campaign

swagger:response createAdOK
*/
type CreateAdOK struct {

	/*
	  In: Body
	*/
	Payload *models.CreateAdResp `json:"body,omitempty"`
}

// NewCreateAdOK creates CreateAdOK with default headers values
func NewCreateAdOK() *CreateAdOK {

	return &CreateAdOK{}
}

// WithPayload adds the payload to the create ad o k response
func (o *CreateAdOK) WithPayload(payload *models.CreateAdResp) *CreateAdOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create ad o k response
func (o *CreateAdOK) SetPayload(payload *models.CreateAdResp) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateAdOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateAdNoContentCode is the HTTP code returned for type CreateAdNoContent
const CreateAdNoContentCode int = 204

/*CreateAdNoContent No Content

swagger:response createAdNoContent
*/
type CreateAdNoContent struct {
}

// NewCreateAdNoContent creates CreateAdNoContent with default headers values
func NewCreateAdNoContent() *CreateAdNoContent {

	return &CreateAdNoContent{}
}

// WriteResponse to the client
func (o *CreateAdNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// CreateAdConflictCode is the HTTP code returned for type CreateAdConflict
const CreateAdConflictCode int = 409

/*CreateAdConflict CampaignAd already exist

swagger:response createAdConflict
*/
type CreateAdConflict struct {
}

// NewCreateAdConflict creates CreateAdConflict with default headers values
func NewCreateAdConflict() *CreateAdConflict {

	return &CreateAdConflict{}
}

// WriteResponse to the client
func (o *CreateAdConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}

// CreateAdInternalServerErrorCode is the HTTP code returned for type CreateAdInternalServerError
const CreateAdInternalServerErrorCode int = 500

/*CreateAdInternalServerError Internal Server Error

swagger:response createAdInternalServerError
*/
type CreateAdInternalServerError struct {
}

// NewCreateAdInternalServerError creates CreateAdInternalServerError with default headers values
func NewCreateAdInternalServerError() *CreateAdInternalServerError {

	return &CreateAdInternalServerError{}
}

// WriteResponse to the client
func (o *CreateAdInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
