// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/jobdoner/vtm-refactor/models"
)

// DeleteFoldersMatchIDOKCode is the HTTP code returned for type DeleteFoldersMatchIDOK
const DeleteFoldersMatchIDOKCode int = 200

/*DeleteFoldersMatchIDOK delete matching folder

swagger:response deleteFoldersMatchIdOK
*/
type DeleteFoldersMatchIDOK struct {

	/*
	  In: Body
	*/
	Payload models.ErrorMess `json:"body,omitempty"`
}

// NewDeleteFoldersMatchIDOK creates DeleteFoldersMatchIDOK with default headers values
func NewDeleteFoldersMatchIDOK() *DeleteFoldersMatchIDOK {

	return &DeleteFoldersMatchIDOK{}
}

// WithPayload adds the payload to the delete folders match Id o k response
func (o *DeleteFoldersMatchIDOK) WithPayload(payload models.ErrorMess) *DeleteFoldersMatchIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete folders match Id o k response
func (o *DeleteFoldersMatchIDOK) SetPayload(payload models.ErrorMess) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteFoldersMatchIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DeleteFoldersMatchIDNoContentCode is the HTTP code returned for type DeleteFoldersMatchIDNoContent
const DeleteFoldersMatchIDNoContentCode int = 204

/*DeleteFoldersMatchIDNoContent no content

swagger:response deleteFoldersMatchIdNoContent
*/
type DeleteFoldersMatchIDNoContent struct {
}

// NewDeleteFoldersMatchIDNoContent creates DeleteFoldersMatchIDNoContent with default headers values
func NewDeleteFoldersMatchIDNoContent() *DeleteFoldersMatchIDNoContent {

	return &DeleteFoldersMatchIDNoContent{}
}

// WriteResponse to the client
func (o *DeleteFoldersMatchIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteFoldersMatchIDInternalServerErrorCode is the HTTP code returned for type DeleteFoldersMatchIDInternalServerError
const DeleteFoldersMatchIDInternalServerErrorCode int = 500

/*DeleteFoldersMatchIDInternalServerError Internal Server Error

swagger:response deleteFoldersMatchIdInternalServerError
*/
type DeleteFoldersMatchIDInternalServerError struct {
}

// NewDeleteFoldersMatchIDInternalServerError creates DeleteFoldersMatchIDInternalServerError with default headers values
func NewDeleteFoldersMatchIDInternalServerError() *DeleteFoldersMatchIDInternalServerError {

	return &DeleteFoldersMatchIDInternalServerError{}
}

// WriteResponse to the client
func (o *DeleteFoldersMatchIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
