// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/jobdoner/vtm-refactor/models"
)

// DeleteFoldersIDOKCode is the HTTP code returned for type DeleteFoldersIDOK
const DeleteFoldersIDOKCode int = 200

/*DeleteFoldersIDOK delete folder

swagger:response deleteFoldersIdOK
*/
type DeleteFoldersIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.ShowFolderResp `json:"body,omitempty"`
}

// NewDeleteFoldersIDOK creates DeleteFoldersIDOK with default headers values
func NewDeleteFoldersIDOK() *DeleteFoldersIDOK {

	return &DeleteFoldersIDOK{}
}

// WithPayload adds the payload to the delete folders Id o k response
func (o *DeleteFoldersIDOK) WithPayload(payload *models.ShowFolderResp) *DeleteFoldersIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete folders Id o k response
func (o *DeleteFoldersIDOK) SetPayload(payload *models.ShowFolderResp) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteFoldersIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteFoldersIDNoContentCode is the HTTP code returned for type DeleteFoldersIDNoContent
const DeleteFoldersIDNoContentCode int = 204

/*DeleteFoldersIDNoContent No Content

swagger:response deleteFoldersIdNoContent
*/
type DeleteFoldersIDNoContent struct {
}

// NewDeleteFoldersIDNoContent creates DeleteFoldersIDNoContent with default headers values
func NewDeleteFoldersIDNoContent() *DeleteFoldersIDNoContent {

	return &DeleteFoldersIDNoContent{}
}

// WriteResponse to the client
func (o *DeleteFoldersIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteFoldersIDInternalServerErrorCode is the HTTP code returned for type DeleteFoldersIDInternalServerError
const DeleteFoldersIDInternalServerErrorCode int = 500

/*DeleteFoldersIDInternalServerError Internal Server Error

swagger:response deleteFoldersIdInternalServerError
*/
type DeleteFoldersIDInternalServerError struct {
}

// NewDeleteFoldersIDInternalServerError creates DeleteFoldersIDInternalServerError with default headers values
func NewDeleteFoldersIDInternalServerError() *DeleteFoldersIDInternalServerError {

	return &DeleteFoldersIDInternalServerError{}
}

// WriteResponse to the client
func (o *DeleteFoldersIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
