// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/jobdoner/vtm-refactor/models"
)

// GetCSVOKCode is the HTTP code returned for type GetCSVOK
const GetCSVOKCode int = 200

/*GetCSVOK get csv

swagger:response getCSVOK
*/
type GetCSVOK struct {

	/*
	  In: Body
	*/
	Payload models.GetFileResp `json:"body,omitempty"`
}

// NewGetCSVOK creates GetCSVOK with default headers values
func NewGetCSVOK() *GetCSVOK {

	return &GetCSVOK{}
}

// WithPayload adds the payload to the get c s v o k response
func (o *GetCSVOK) WithPayload(payload models.GetFileResp) *GetCSVOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get c s v o k response
func (o *GetCSVOK) SetPayload(payload models.GetFileResp) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCSVOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetCSVNoContentCode is the HTTP code returned for type GetCSVNoContent
const GetCSVNoContentCode int = 204

/*GetCSVNoContent No Content

swagger:response getCSVNoContent
*/
type GetCSVNoContent struct {
}

// NewGetCSVNoContent creates GetCSVNoContent with default headers values
func NewGetCSVNoContent() *GetCSVNoContent {

	return &GetCSVNoContent{}
}

// WriteResponse to the client
func (o *GetCSVNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// GetCSVInternalServerErrorCode is the HTTP code returned for type GetCSVInternalServerError
const GetCSVInternalServerErrorCode int = 500

/*GetCSVInternalServerError Internal Server Error

swagger:response getCSVInternalServerError
*/
type GetCSVInternalServerError struct {
}

// NewGetCSVInternalServerError creates GetCSVInternalServerError with default headers values
func NewGetCSVInternalServerError() *GetCSVInternalServerError {

	return &GetCSVInternalServerError{}
}

// WriteResponse to the client
func (o *GetCSVInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
