// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/jobdoner/vtm-refactor/models"
)

// GetSettingsTechOKCode is the HTTP code returned for type GetSettingsTechOK
const GetSettingsTechOKCode int = 200

/*GetSettingsTechOK get

swagger:response getSettingsTechOK
*/
type GetSettingsTechOK struct {

	/*
	  In: Body
	*/
	Payload models.GetSettingsObjectResp `json:"body,omitempty"`
}

// NewGetSettingsTechOK creates GetSettingsTechOK with default headers values
func NewGetSettingsTechOK() *GetSettingsTechOK {

	return &GetSettingsTechOK{}
}

// WithPayload adds the payload to the get settings tech o k response
func (o *GetSettingsTechOK) WithPayload(payload models.GetSettingsObjectResp) *GetSettingsTechOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get settings tech o k response
func (o *GetSettingsTechOK) SetPayload(payload models.GetSettingsObjectResp) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSettingsTechOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.GetSettingsObjectResp{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetSettingsTechNoContentCode is the HTTP code returned for type GetSettingsTechNoContent
const GetSettingsTechNoContentCode int = 204

/*GetSettingsTechNoContent No Content

swagger:response getSettingsTechNoContent
*/
type GetSettingsTechNoContent struct {
}

// NewGetSettingsTechNoContent creates GetSettingsTechNoContent with default headers values
func NewGetSettingsTechNoContent() *GetSettingsTechNoContent {

	return &GetSettingsTechNoContent{}
}

// WriteResponse to the client
func (o *GetSettingsTechNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// GetSettingsTechInternalServerErrorCode is the HTTP code returned for type GetSettingsTechInternalServerError
const GetSettingsTechInternalServerErrorCode int = 500

/*GetSettingsTechInternalServerError Internal Server Error

swagger:response getSettingsTechInternalServerError
*/
type GetSettingsTechInternalServerError struct {
}

// NewGetSettingsTechInternalServerError creates GetSettingsTechInternalServerError with default headers values
func NewGetSettingsTechInternalServerError() *GetSettingsTechInternalServerError {

	return &GetSettingsTechInternalServerError{}
}

// WriteResponse to the client
func (o *GetSettingsTechInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
