// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/jobdoner/vtm-refactor/models"
)

// GetSettingsOKCode is the HTTP code returned for type GetSettingsOK
const GetSettingsOKCode int = 200

/*GetSettingsOK get settings by list name

swagger:response getSettingsOK
*/
type GetSettingsOK struct {

	/*
	  In: Body
	*/
	Payload models.GetSettingsResp `json:"body,omitempty"`
}

// NewGetSettingsOK creates GetSettingsOK with default headers values
func NewGetSettingsOK() *GetSettingsOK {

	return &GetSettingsOK{}
}

// WithPayload adds the payload to the get settings o k response
func (o *GetSettingsOK) WithPayload(payload models.GetSettingsResp) *GetSettingsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get settings o k response
func (o *GetSettingsOK) SetPayload(payload models.GetSettingsResp) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSettingsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetSettingsNoContentCode is the HTTP code returned for type GetSettingsNoContent
const GetSettingsNoContentCode int = 204

/*GetSettingsNoContent No Content

swagger:response getSettingsNoContent
*/
type GetSettingsNoContent struct {
}

// NewGetSettingsNoContent creates GetSettingsNoContent with default headers values
func NewGetSettingsNoContent() *GetSettingsNoContent {

	return &GetSettingsNoContent{}
}

// WriteResponse to the client
func (o *GetSettingsNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// GetSettingsInternalServerErrorCode is the HTTP code returned for type GetSettingsInternalServerError
const GetSettingsInternalServerErrorCode int = 500

/*GetSettingsInternalServerError Internal Server Error

swagger:response getSettingsInternalServerError
*/
type GetSettingsInternalServerError struct {
}

// NewGetSettingsInternalServerError creates GetSettingsInternalServerError with default headers values
func NewGetSettingsInternalServerError() *GetSettingsInternalServerError {

	return &GetSettingsInternalServerError{}
}

// WriteResponse to the client
func (o *GetSettingsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
