// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/jobdoner/vtm-refactor/models"
)

// GetFoldersOKCode is the HTTP code returned for type GetFoldersOK
const GetFoldersOKCode int = 200

/*GetFoldersOK get folders

swagger:response getFoldersOK
*/
type GetFoldersOK struct {

	/*
	  In: Body
	*/
	Payload *models.GetFoldersResp `json:"body,omitempty"`
}

// NewGetFoldersOK creates GetFoldersOK with default headers values
func NewGetFoldersOK() *GetFoldersOK {

	return &GetFoldersOK{}
}

// WithPayload adds the payload to the get folders o k response
func (o *GetFoldersOK) WithPayload(payload *models.GetFoldersResp) *GetFoldersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get folders o k response
func (o *GetFoldersOK) SetPayload(payload *models.GetFoldersResp) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFoldersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetFoldersNoContentCode is the HTTP code returned for type GetFoldersNoContent
const GetFoldersNoContentCode int = 204

/*GetFoldersNoContent no content

swagger:response getFoldersNoContent
*/
type GetFoldersNoContent struct {
}

// NewGetFoldersNoContent creates GetFoldersNoContent with default headers values
func NewGetFoldersNoContent() *GetFoldersNoContent {

	return &GetFoldersNoContent{}
}

// WriteResponse to the client
func (o *GetFoldersNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// GetFoldersInternalServerErrorCode is the HTTP code returned for type GetFoldersInternalServerError
const GetFoldersInternalServerErrorCode int = 500

/*GetFoldersInternalServerError Internal Server Error

swagger:response getFoldersInternalServerError
*/
type GetFoldersInternalServerError struct {
}

// NewGetFoldersInternalServerError creates GetFoldersInternalServerError with default headers values
func NewGetFoldersInternalServerError() *GetFoldersInternalServerError {

	return &GetFoldersInternalServerError{}
}

// WriteResponse to the client
func (o *GetFoldersInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
