// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/jobdoner/vtm-refactor/models"
)

// GetSettingsObjectOKCode is the HTTP code returned for type GetSettingsObjectOK
const GetSettingsObjectOKCode int = 200

/*GetSettingsObjectOK get

swagger:response getSettingsObjectOK
*/
type GetSettingsObjectOK struct {

	/*
	  In: Body
	*/
	Payload models.GetSettingsObjectResp `json:"body,omitempty"`
}

// NewGetSettingsObjectOK creates GetSettingsObjectOK with default headers values
func NewGetSettingsObjectOK() *GetSettingsObjectOK {

	return &GetSettingsObjectOK{}
}

// WithPayload adds the payload to the get settings object o k response
func (o *GetSettingsObjectOK) WithPayload(payload models.GetSettingsObjectResp) *GetSettingsObjectOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get settings object o k response
func (o *GetSettingsObjectOK) SetPayload(payload models.GetSettingsObjectResp) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSettingsObjectOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.GetSettingsObjectResp{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetSettingsObjectNoContentCode is the HTTP code returned for type GetSettingsObjectNoContent
const GetSettingsObjectNoContentCode int = 204

/*GetSettingsObjectNoContent No Content

swagger:response getSettingsObjectNoContent
*/
type GetSettingsObjectNoContent struct {
}

// NewGetSettingsObjectNoContent creates GetSettingsObjectNoContent with default headers values
func NewGetSettingsObjectNoContent() *GetSettingsObjectNoContent {

	return &GetSettingsObjectNoContent{}
}

// WriteResponse to the client
func (o *GetSettingsObjectNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// GetSettingsObjectInternalServerErrorCode is the HTTP code returned for type GetSettingsObjectInternalServerError
const GetSettingsObjectInternalServerErrorCode int = 500

/*GetSettingsObjectInternalServerError Internal Server Error

swagger:response getSettingsObjectInternalServerError
*/
type GetSettingsObjectInternalServerError struct {
}

// NewGetSettingsObjectInternalServerError creates GetSettingsObjectInternalServerError with default headers values
func NewGetSettingsObjectInternalServerError() *GetSettingsObjectInternalServerError {

	return &GetSettingsObjectInternalServerError{}
}

// WriteResponse to the client
func (o *GetSettingsObjectInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
