// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/jobdoner/vtm-refactor/models"
)

// GetCampaignOKCode is the HTTP code returned for type GetCampaignOK
const GetCampaignOKCode int = 200

/*GetCampaignOK Get Dick sucker

swagger:response getCampaignOK
*/
type GetCampaignOK struct {

	/*
	  In: Body
	*/
	Payload *models.GetCampaignResp `json:"body,omitempty"`
}

// NewGetCampaignOK creates GetCampaignOK with default headers values
func NewGetCampaignOK() *GetCampaignOK {

	return &GetCampaignOK{}
}

// WithPayload adds the payload to the get campaign o k response
func (o *GetCampaignOK) WithPayload(payload *models.GetCampaignResp) *GetCampaignOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get campaign o k response
func (o *GetCampaignOK) SetPayload(payload *models.GetCampaignResp) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCampaignOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCampaignNoContentCode is the HTTP code returned for type GetCampaignNoContent
const GetCampaignNoContentCode int = 204

/*GetCampaignNoContent No Content

swagger:response getCampaignNoContent
*/
type GetCampaignNoContent struct {
}

// NewGetCampaignNoContent creates GetCampaignNoContent with default headers values
func NewGetCampaignNoContent() *GetCampaignNoContent {

	return &GetCampaignNoContent{}
}

// WriteResponse to the client
func (o *GetCampaignNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// GetCampaignInternalServerErrorCode is the HTTP code returned for type GetCampaignInternalServerError
const GetCampaignInternalServerErrorCode int = 500

/*GetCampaignInternalServerError Internal Server Error

swagger:response getCampaignInternalServerError
*/
type GetCampaignInternalServerError struct {
}

// NewGetCampaignInternalServerError creates GetCampaignInternalServerError with default headers values
func NewGetCampaignInternalServerError() *GetCampaignInternalServerError {

	return &GetCampaignInternalServerError{}
}

// WriteResponse to the client
func (o *GetCampaignInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
