// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetSettingsObjectHandlerFunc turns a function with the right signature into a get settings object handler
type GetSettingsObjectHandlerFunc func(GetSettingsObjectParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSettingsObjectHandlerFunc) Handle(params GetSettingsObjectParams) middleware.Responder {
	return fn(params)
}

// GetSettingsObjectHandler interface for that can handle valid get settings object params
type GetSettingsObjectHandler interface {
	Handle(GetSettingsObjectParams) middleware.Responder
}

// NewGetSettingsObject creates a new http.Handler for the get settings object operation
func NewGetSettingsObject(ctx *middleware.Context, handler GetSettingsObjectHandler) *GetSettingsObject {
	return &GetSettingsObject{Context: ctx, Handler: handler}
}

/*GetSettingsObject swagger:route GET /settings/object getSettingsObject

GetSettingsObject get settings object API

*/
type GetSettingsObject struct {
	Context *middleware.Context
	Handler GetSettingsObjectHandler
}

func (o *GetSettingsObject) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetSettingsObjectParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
