// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/jobdoner/vtm-refactor/models"
)

// GetFoldersIDOKCode is the HTTP code returned for type GetFoldersIDOK
const GetFoldersIDOKCode int = 200

/*GetFoldersIDOK show folder

swagger:response getFoldersIdOK
*/
type GetFoldersIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.ShowFolderResp `json:"body,omitempty"`
}

// NewGetFoldersIDOK creates GetFoldersIDOK with default headers values
func NewGetFoldersIDOK() *GetFoldersIDOK {

	return &GetFoldersIDOK{}
}

// WithPayload adds the payload to the get folders Id o k response
func (o *GetFoldersIDOK) WithPayload(payload *models.ShowFolderResp) *GetFoldersIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get folders Id o k response
func (o *GetFoldersIDOK) SetPayload(payload *models.ShowFolderResp) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFoldersIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetFoldersIDNoContentCode is the HTTP code returned for type GetFoldersIDNoContent
const GetFoldersIDNoContentCode int = 204

/*GetFoldersIDNoContent No Content

swagger:response getFoldersIdNoContent
*/
type GetFoldersIDNoContent struct {
}

// NewGetFoldersIDNoContent creates GetFoldersIDNoContent with default headers values
func NewGetFoldersIDNoContent() *GetFoldersIDNoContent {

	return &GetFoldersIDNoContent{}
}

// WriteResponse to the client
func (o *GetFoldersIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// GetFoldersIDInternalServerErrorCode is the HTTP code returned for type GetFoldersIDInternalServerError
const GetFoldersIDInternalServerErrorCode int = 500

/*GetFoldersIDInternalServerError Internal Server Error

swagger:response getFoldersIdInternalServerError
*/
type GetFoldersIDInternalServerError struct {
}

// NewGetFoldersIDInternalServerError creates GetFoldersIDInternalServerError with default headers values
func NewGetFoldersIDInternalServerError() *GetFoldersIDInternalServerError {

	return &GetFoldersIDInternalServerError{}
}

// WriteResponse to the client
func (o *GetFoldersIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
