// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetCSVHandlerFunc turns a function with the right signature into a get c s v handler
type GetCSVHandlerFunc func(GetCSVParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCSVHandlerFunc) Handle(params GetCSVParams) middleware.Responder {
	return fn(params)
}

// GetCSVHandler interface for that can handle valid get c s v params
type GetCSVHandler interface {
	Handle(GetCSVParams) middleware.Responder
}

// NewGetCSV creates a new http.Handler for the get c s v operation
func NewGetCSV(ctx *middleware.Context, handler GetCSVHandler) *GetCSV {
	return &GetCSV{Context: ctx, Handler: handler}
}

/*GetCSV swagger:route GET /csv getCSV

GetCSV get c s v API

*/
type GetCSV struct {
	Context *middleware.Context
	Handler GetCSVHandler
}

func (o *GetCSV) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetCSVParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
