// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/jobdoner/vtm-refactor/models"
)

// GetAdgroupOKCode is the HTTP code returned for type GetAdgroupOK
const GetAdgroupOKCode int = 200

/*GetAdgroupOK get adgroups

swagger:response getAdgroupOK
*/
type GetAdgroupOK struct {

	/*
	  In: Body
	*/
	Payload *models.GetAdGroupResp `json:"body,omitempty"`
}

// NewGetAdgroupOK creates GetAdgroupOK with default headers values
func NewGetAdgroupOK() *GetAdgroupOK {

	return &GetAdgroupOK{}
}

// WithPayload adds the payload to the get adgroup o k response
func (o *GetAdgroupOK) WithPayload(payload *models.GetAdGroupResp) *GetAdgroupOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get adgroup o k response
func (o *GetAdgroupOK) SetPayload(payload *models.GetAdGroupResp) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAdgroupOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
