// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/jobdoner/vtm-refactor/models"
)

// GetTargetsOKCode is the HTTP code returned for type GetTargetsOK
const GetTargetsOKCode int = 200

/*GetTargetsOK get csv

swagger:response getTargetsOK
*/
type GetTargetsOK struct {

	/*
	  In: Body
	*/
	Payload models.GetFileResp `json:"body,omitempty"`
}

// NewGetTargetsOK creates GetTargetsOK with default headers values
func NewGetTargetsOK() *GetTargetsOK {

	return &GetTargetsOK{}
}

// WithPayload adds the payload to the get targets o k response
func (o *GetTargetsOK) WithPayload(payload models.GetFileResp) *GetTargetsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get targets o k response
func (o *GetTargetsOK) SetPayload(payload models.GetFileResp) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTargetsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetTargetsNoContentCode is the HTTP code returned for type GetTargetsNoContent
const GetTargetsNoContentCode int = 204

/*GetTargetsNoContent No Content

swagger:response getTargetsNoContent
*/
type GetTargetsNoContent struct {
}

// NewGetTargetsNoContent creates GetTargetsNoContent with default headers values
func NewGetTargetsNoContent() *GetTargetsNoContent {

	return &GetTargetsNoContent{}
}

// WriteResponse to the client
func (o *GetTargetsNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// GetTargetsInternalServerErrorCode is the HTTP code returned for type GetTargetsInternalServerError
const GetTargetsInternalServerErrorCode int = 500

/*GetTargetsInternalServerError Internal Server Error

swagger:response getTargetsInternalServerError
*/
type GetTargetsInternalServerError struct {
}

// NewGetTargetsInternalServerError creates GetTargetsInternalServerError with default headers values
func NewGetTargetsInternalServerError() *GetTargetsInternalServerError {

	return &GetTargetsInternalServerError{}
}

// WriteResponse to the client
func (o *GetTargetsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
