// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/jobdoner/vtm-refactor/models"
)

// GetCampaignIDOKCode is the HTTP code returned for type GetCampaignIDOK
const GetCampaignIDOKCode int = 200

/*GetCampaignIDOK show campaign

swagger:response getCampaignIdOK
*/
type GetCampaignIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.ShowCampaignResp `json:"body,omitempty"`
}

// NewGetCampaignIDOK creates GetCampaignIDOK with default headers values
func NewGetCampaignIDOK() *GetCampaignIDOK {

	return &GetCampaignIDOK{}
}

// WithPayload adds the payload to the get campaign Id o k response
func (o *GetCampaignIDOK) WithPayload(payload *models.ShowCampaignResp) *GetCampaignIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get campaign Id o k response
func (o *GetCampaignIDOK) SetPayload(payload *models.ShowCampaignResp) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCampaignIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCampaignIDNoContentCode is the HTTP code returned for type GetCampaignIDNoContent
const GetCampaignIDNoContentCode int = 204

/*GetCampaignIDNoContent No Content

swagger:response getCampaignIdNoContent
*/
type GetCampaignIDNoContent struct {
}

// NewGetCampaignIDNoContent creates GetCampaignIDNoContent with default headers values
func NewGetCampaignIDNoContent() *GetCampaignIDNoContent {

	return &GetCampaignIDNoContent{}
}

// WriteResponse to the client
func (o *GetCampaignIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// GetCampaignIDInternalServerErrorCode is the HTTP code returned for type GetCampaignIDInternalServerError
const GetCampaignIDInternalServerErrorCode int = 500

/*GetCampaignIDInternalServerError Internal Server Error

swagger:response getCampaignIdInternalServerError
*/
type GetCampaignIDInternalServerError struct {
}

// NewGetCampaignIDInternalServerError creates GetCampaignIDInternalServerError with default headers values
func NewGetCampaignIDInternalServerError() *GetCampaignIDInternalServerError {

	return &GetCampaignIDInternalServerError{}
}

// WriteResponse to the client
func (o *GetCampaignIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
