// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetFoldersIDHandlerFunc turns a function with the right signature into a get folders ID handler
type GetFoldersIDHandlerFunc func(GetFoldersIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFoldersIDHandlerFunc) Handle(params GetFoldersIDParams) middleware.Responder {
	return fn(params)
}

// GetFoldersIDHandler interface for that can handle valid get folders ID params
type GetFoldersIDHandler interface {
	Handle(GetFoldersIDParams) middleware.Responder
}

// NewGetFoldersID creates a new http.Handler for the get folders ID operation
func NewGetFoldersID(ctx *middleware.Context, handler GetFoldersIDHandler) *GetFoldersID {
	return &GetFoldersID{Context: ctx, Handler: handler}
}

/*GetFoldersID swagger:route GET /folders/{id} getFoldersId

GetFoldersID get folders ID API

*/
type GetFoldersID struct {
	Context *middleware.Context
	Handler GetFoldersIDHandler
}

func (o *GetFoldersID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetFoldersIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
