// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/jobdoner/vtm-refactor/models"
)

// ListMatchingFoldersOKCode is the HTTP code returned for type ListMatchingFoldersOK
const ListMatchingFoldersOKCode int = 200

/*ListMatchingFoldersOK list folders

swagger:response listMatchingFoldersOK
*/
type ListMatchingFoldersOK struct {

	/*
	  In: Body
	*/
	Payload models.ListMatchingFoldersResp `json:"body,omitempty"`
}

// NewListMatchingFoldersOK creates ListMatchingFoldersOK with default headers values
func NewListMatchingFoldersOK() *ListMatchingFoldersOK {

	return &ListMatchingFoldersOK{}
}

// WithPayload adds the payload to the list matching folders o k response
func (o *ListMatchingFoldersOK) WithPayload(payload models.ListMatchingFoldersResp) *ListMatchingFoldersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list matching folders o k response
func (o *ListMatchingFoldersOK) SetPayload(payload models.ListMatchingFoldersResp) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListMatchingFoldersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.ListMatchingFoldersResp{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ListMatchingFoldersNoContentCode is the HTTP code returned for type ListMatchingFoldersNoContent
const ListMatchingFoldersNoContentCode int = 204

/*ListMatchingFoldersNoContent no content

swagger:response listMatchingFoldersNoContent
*/
type ListMatchingFoldersNoContent struct {
}

// NewListMatchingFoldersNoContent creates ListMatchingFoldersNoContent with default headers values
func NewListMatchingFoldersNoContent() *ListMatchingFoldersNoContent {

	return &ListMatchingFoldersNoContent{}
}

// WriteResponse to the client
func (o *ListMatchingFoldersNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// ListMatchingFoldersInternalServerErrorCode is the HTTP code returned for type ListMatchingFoldersInternalServerError
const ListMatchingFoldersInternalServerErrorCode int = 500

/*ListMatchingFoldersInternalServerError Internal Server Error

swagger:response listMatchingFoldersInternalServerError
*/
type ListMatchingFoldersInternalServerError struct {
}

// NewListMatchingFoldersInternalServerError creates ListMatchingFoldersInternalServerError with default headers values
func NewListMatchingFoldersInternalServerError() *ListMatchingFoldersInternalServerError {

	return &ListMatchingFoldersInternalServerError{}
}

// WriteResponse to the client
func (o *ListMatchingFoldersInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
