// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/jobdoner/vtm-refactor/models"
)

// ListVideosOKCode is the HTTP code returned for type ListVideosOK
const ListVideosOKCode int = 200

/*ListVideosOK list videos

swagger:response listVideosOK
*/
type ListVideosOK struct {

	/*
	  In: Body
	*/
	Payload models.ListVideosResp `json:"body,omitempty"`
}

// NewListVideosOK creates ListVideosOK with default headers values
func NewListVideosOK() *ListVideosOK {

	return &ListVideosOK{}
}

// WithPayload adds the payload to the list videos o k response
func (o *ListVideosOK) WithPayload(payload models.ListVideosResp) *ListVideosOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list videos o k response
func (o *ListVideosOK) SetPayload(payload models.ListVideosResp) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListVideosOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.ListVideosResp{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ListVideosNoContentCode is the HTTP code returned for type ListVideosNoContent
const ListVideosNoContentCode int = 204

/*ListVideosNoContent No Content

swagger:response listVideosNoContent
*/
type ListVideosNoContent struct {
}

// NewListVideosNoContent creates ListVideosNoContent with default headers values
func NewListVideosNoContent() *ListVideosNoContent {

	return &ListVideosNoContent{}
}

// WriteResponse to the client
func (o *ListVideosNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// ListVideosInternalServerErrorCode is the HTTP code returned for type ListVideosInternalServerError
const ListVideosInternalServerErrorCode int = 500

/*ListVideosInternalServerError Internal Server Error

swagger:response listVideosInternalServerError
*/
type ListVideosInternalServerError struct {
}

// NewListVideosInternalServerError creates ListVideosInternalServerError with default headers values
func NewListVideosInternalServerError() *ListVideosInternalServerError {

	return &ListVideosInternalServerError{}
}

// WriteResponse to the client
func (o *ListVideosInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
