// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListVideosHandlerFunc turns a function with the right signature into a list videos handler
type ListVideosHandlerFunc func(ListVideosParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListVideosHandlerFunc) Handle(params ListVideosParams) middleware.Responder {
	return fn(params)
}

// ListVideosHandler interface for that can handle valid list videos params
type ListVideosHandler interface {
	Handle(ListVideosParams) middleware.Responder
}

// NewListVideos creates a new http.Handler for the list videos operation
func NewListVideos(ctx *middleware.Context, handler ListVideosHandler) *ListVideos {
	return &ListVideos{Context: ctx, Handler: handler}
}

/*ListVideos swagger:route GET /video/folders/{folderID} listVideos

ListVideos list videos API

*/
type ListVideos struct {
	Context *middleware.Context
	Handler ListVideosHandler
}

func (o *ListVideos) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListVideosParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
