// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PatchFoldersIDHandlerFunc turns a function with the right signature into a patch folders ID handler
type PatchFoldersIDHandlerFunc func(PatchFoldersIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PatchFoldersIDHandlerFunc) Handle(params PatchFoldersIDParams) middleware.Responder {
	return fn(params)
}

// PatchFoldersIDHandler interface for that can handle valid patch folders ID params
type PatchFoldersIDHandler interface {
	Handle(PatchFoldersIDParams) middleware.Responder
}

// NewPatchFoldersID creates a new http.Handler for the patch folders ID operation
func NewPatchFoldersID(ctx *middleware.Context, handler PatchFoldersIDHandler) *PatchFoldersID {
	return &PatchFoldersID{Context: ctx, Handler: handler}
}

/*PatchFoldersID swagger:route PATCH /folders/{id} patchFoldersId

PatchFoldersID patch folders ID API

*/
type PatchFoldersID struct {
	Context *middleware.Context
	Handler PatchFoldersIDHandler
}

func (o *PatchFoldersID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPatchFoldersIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
