// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PatchCampaignIDHandlerFunc turns a function with the right signature into a patch campaign ID handler
type PatchCampaignIDHandlerFunc func(PatchCampaignIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PatchCampaignIDHandlerFunc) Handle(params PatchCampaignIDParams) middleware.Responder {
	return fn(params)
}

// PatchCampaignIDHandler interface for that can handle valid patch campaign ID params
type PatchCampaignIDHandler interface {
	Handle(PatchCampaignIDParams) middleware.Responder
}

// NewPatchCampaignID creates a new http.Handler for the patch campaign ID operation
func NewPatchCampaignID(ctx *middleware.Context, handler PatchCampaignIDHandler) *PatchCampaignID {
	return &PatchCampaignID{Context: ctx, Handler: handler}
}

/*PatchCampaignID swagger:route PATCH /campaign/{id} patchCampaignId

PatchCampaignID patch campaign ID API

*/
type PatchCampaignID struct {
	Context *middleware.Context
	Handler PatchCampaignIDHandler
}

func (o *PatchCampaignID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPatchCampaignIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
