// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/jobdoner/vtm-refactor/models"
)

// PostVideoOKCode is the HTTP code returned for type PostVideoOK
const PostVideoOKCode int = 200

/*PostVideoOK Create video

swagger:response postVideoOK
*/
type PostVideoOK struct {

	/*
	  In: Body
	*/
	Payload models.ListVideosResp `json:"body,omitempty"`
}

// NewPostVideoOK creates PostVideoOK with default headers values
func NewPostVideoOK() *PostVideoOK {

	return &PostVideoOK{}
}

// WithPayload adds the payload to the post video o k response
func (o *PostVideoOK) WithPayload(payload models.ListVideosResp) *PostVideoOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post video o k response
func (o *PostVideoOK) SetPayload(payload models.ListVideosResp) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostVideoOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.ListVideosResp{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PostVideoNoContentCode is the HTTP code returned for type PostVideoNoContent
const PostVideoNoContentCode int = 204

/*PostVideoNoContent No Content

swagger:response postVideoNoContent
*/
type PostVideoNoContent struct {
}

// NewPostVideoNoContent creates PostVideoNoContent with default headers values
func NewPostVideoNoContent() *PostVideoNoContent {

	return &PostVideoNoContent{}
}

// WriteResponse to the client
func (o *PostVideoNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// PostVideoConflictCode is the HTTP code returned for type PostVideoConflict
const PostVideoConflictCode int = 409

/*PostVideoConflict Video already exist

swagger:response postVideoConflict
*/
type PostVideoConflict struct {
}

// NewPostVideoConflict creates PostVideoConflict with default headers values
func NewPostVideoConflict() *PostVideoConflict {

	return &PostVideoConflict{}
}

// WriteResponse to the client
func (o *PostVideoConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}

// PostVideoInternalServerErrorCode is the HTTP code returned for type PostVideoInternalServerError
const PostVideoInternalServerErrorCode int = 500

/*PostVideoInternalServerError Internal Server Error

swagger:response postVideoInternalServerError
*/
type PostVideoInternalServerError struct {
}

// NewPostVideoInternalServerError creates PostVideoInternalServerError with default headers values
func NewPostVideoInternalServerError() *PostVideoInternalServerError {

	return &PostVideoInternalServerError{}
}

// WriteResponse to the client
func (o *PostVideoInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
