// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostImportTargetsHandlerFunc turns a function with the right signature into a post import targets handler
type PostImportTargetsHandlerFunc func(PostImportTargetsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostImportTargetsHandlerFunc) Handle(params PostImportTargetsParams) middleware.Responder {
	return fn(params)
}

// PostImportTargetsHandler interface for that can handle valid post import targets params
type PostImportTargetsHandler interface {
	Handle(PostImportTargetsParams) middleware.Responder
}

// NewPostImportTargets creates a new http.Handler for the post import targets operation
func NewPostImportTargets(ctx *middleware.Context, handler PostImportTargetsHandler) *PostImportTargets {
	return &PostImportTargets{Context: ctx, Handler: handler}
}

/*PostImportTargets swagger:route POST /import/targets postImportTargets

Uploads targets file.

*/
type PostImportTargets struct {
	Context *middleware.Context
	Handler PostImportTargetsHandler
}

func (o *PostImportTargets) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostImportTargetsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
