// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostImportTargetsOKCode is the HTTP code returned for type PostImportTargetsOK
const PostImportTargetsOKCode int = 200

/*PostImportTargetsOK import targets

swagger:response postImportTargetsOK
*/
type PostImportTargetsOK struct {
}

// NewPostImportTargetsOK creates PostImportTargetsOK with default headers values
func NewPostImportTargetsOK() *PostImportTargetsOK {

	return &PostImportTargetsOK{}
}

// WriteResponse to the client
func (o *PostImportTargetsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostImportTargetsInternalServerErrorCode is the HTTP code returned for type PostImportTargetsInternalServerError
const PostImportTargetsInternalServerErrorCode int = 500

/*PostImportTargetsInternalServerError Internal Server Error

swagger:response postImportTargetsInternalServerError
*/
type PostImportTargetsInternalServerError struct {
}

// NewPostImportTargetsInternalServerError creates PostImportTargetsInternalServerError with default headers values
func NewPostImportTargetsInternalServerError() *PostImportTargetsInternalServerError {

	return &PostImportTargetsInternalServerError{}
}

// WriteResponse to the client
func (o *PostImportTargetsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
