// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"mime/multipart"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
)

// NewPostImportTargetsParams creates a new PostImportTargetsParams object
// no default values defined in spec.
func NewPostImportTargetsParams() PostImportTargetsParams {

	return PostImportTargetsParams{}
}

// PostImportTargetsParams contains all the bound params for the post import targets operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostImportTargets
type PostImportTargetsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*file
	  In: formData
	*/
	UploadFile io.ReadCloser
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostImportTargetsParams() beforehand.
func (o *PostImportTargetsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if err := r.ParseMultipartForm(32 << 20); err != nil {
		if err != http.ErrNotMultipart {
			return errors.New(400, "%v", err)
		} else if err := r.ParseForm(); err != nil {
			return errors.New(400, "%v", err)
		}
	}

	uploadFile, uploadFileHeader, err := r.FormFile("uploadFile")
	if err != nil && err != http.ErrMissingFile {
		res = append(res, errors.New(400, "reading file %q failed: %v", "uploadFile", err))
	} else if err == http.ErrMissingFile {
		// no-op for missing but optional file parameter
	} else if err := o.bindUploadFile(uploadFile, uploadFileHeader); err != nil {
		res = append(res, err)
	} else {
		o.UploadFile = &runtime.File{Data: uploadFile, Header: uploadFileHeader}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindUploadFile binds file parameter UploadFile.
//
// The only supported validations on files are MinLength and MaxLength
func (o *PostImportTargetsParams) bindUploadFile(file multipart.File, header *multipart.FileHeader) error {
	return nil
}
