// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ShowAdgroupHandlerFunc turns a function with the right signature into a show adgroup handler
type ShowAdgroupHandlerFunc func(ShowAdgroupParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ShowAdgroupHandlerFunc) Handle(params ShowAdgroupParams) middleware.Responder {
	return fn(params)
}

// ShowAdgroupHandler interface for that can handle valid show adgroup params
type ShowAdgroupHandler interface {
	Handle(ShowAdgroupParams) middleware.Responder
}

// NewShowAdgroup creates a new http.Handler for the show adgroup operation
func NewShowAdgroup(ctx *middleware.Context, handler ShowAdgroupHandler) *ShowAdgroup {
	return &ShowAdgroup{Context: ctx, Handler: handler}
}

/*ShowAdgroup swagger:route GET /adgroup/{id} showAdgroup

ShowAdgroup show adgroup API

*/
type ShowAdgroup struct {
	Context *middleware.Context
	Handler ShowAdgroupHandler
}

func (o *ShowAdgroup) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewShowAdgroupParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
