// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/jobdoner/vtm-refactor/models"
)

// ShowAdgroupOKCode is the HTTP code returned for type ShowAdgroupOK
const ShowAdgroupOKCode int = 200

/*ShowAdgroupOK show adgroup

swagger:response showAdgroupOK
*/
type ShowAdgroupOK struct {

	/*
	  In: Body
	*/
	Payload *models.ShowAdGroupResp `json:"body,omitempty"`
}

// NewShowAdgroupOK creates ShowAdgroupOK with default headers values
func NewShowAdgroupOK() *ShowAdgroupOK {

	return &ShowAdgroupOK{}
}

// WithPayload adds the payload to the show adgroup o k response
func (o *ShowAdgroupOK) WithPayload(payload *models.ShowAdGroupResp) *ShowAdgroupOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the show adgroup o k response
func (o *ShowAdgroupOK) SetPayload(payload *models.ShowAdGroupResp) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ShowAdgroupOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ShowAdgroupNoContentCode is the HTTP code returned for type ShowAdgroupNoContent
const ShowAdgroupNoContentCode int = 204

/*ShowAdgroupNoContent No Content

swagger:response showAdgroupNoContent
*/
type ShowAdgroupNoContent struct {
}

// NewShowAdgroupNoContent creates ShowAdgroupNoContent with default headers values
func NewShowAdgroupNoContent() *ShowAdgroupNoContent {

	return &ShowAdgroupNoContent{}
}

// WriteResponse to the client
func (o *ShowAdgroupNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// ShowAdgroupInternalServerErrorCode is the HTTP code returned for type ShowAdgroupInternalServerError
const ShowAdgroupInternalServerErrorCode int = 500

/*ShowAdgroupInternalServerError Internal Server Error

swagger:response showAdgroupInternalServerError
*/
type ShowAdgroupInternalServerError struct {
}

// NewShowAdgroupInternalServerError creates ShowAdgroupInternalServerError with default headers values
func NewShowAdgroupInternalServerError() *ShowAdgroupInternalServerError {

	return &ShowAdgroupInternalServerError{}
}

// WriteResponse to the client
func (o *ShowAdgroupInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
