// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UploadVideoOKCode is the HTTP code returned for type UploadVideoOK
const UploadVideoOKCode int = 200

/*UploadVideoOK Upload video

swagger:response uploadVideoOK
*/
type UploadVideoOK struct {
}

// NewUploadVideoOK creates UploadVideoOK with default headers values
func NewUploadVideoOK() *UploadVideoOK {

	return &UploadVideoOK{}
}

// WriteResponse to the client
func (o *UploadVideoOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// UploadVideoNoContentCode is the HTTP code returned for type UploadVideoNoContent
const UploadVideoNoContentCode int = 204

/*UploadVideoNoContent No Content

swagger:response uploadVideoNoContent
*/
type UploadVideoNoContent struct {
}

// NewUploadVideoNoContent creates UploadVideoNoContent with default headers values
func NewUploadVideoNoContent() *UploadVideoNoContent {

	return &UploadVideoNoContent{}
}

// WriteResponse to the client
func (o *UploadVideoNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// UploadVideoConflictCode is the HTTP code returned for type UploadVideoConflict
const UploadVideoConflictCode int = 409

/*UploadVideoConflict Video already exist

swagger:response uploadVideoConflict
*/
type UploadVideoConflict struct {
}

// NewUploadVideoConflict creates UploadVideoConflict with default headers values
func NewUploadVideoConflict() *UploadVideoConflict {

	return &UploadVideoConflict{}
}

// WriteResponse to the client
func (o *UploadVideoConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}

// UploadVideoInternalServerErrorCode is the HTTP code returned for type UploadVideoInternalServerError
const UploadVideoInternalServerErrorCode int = 500

/*UploadVideoInternalServerError Internal Server Error

swagger:response uploadVideoInternalServerError
*/
type UploadVideoInternalServerError struct {
}

// NewUploadVideoInternalServerError creates UploadVideoInternalServerError with default headers values
func NewUploadVideoInternalServerError() *UploadVideoInternalServerError {

	return &UploadVideoInternalServerError{}
}

// WriteResponse to the client
func (o *UploadVideoInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
