// Code generated by go-swagger; DO NOT EDIT.

// Package restapi vtm app
//
//  vtm app
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 0.0.2
//
//  Consumes:
//    - application/json
//    - multipart/form-data
//
//  Produces:
//    - application/octet-stream
//    - application/json
//
// swagger:meta
package restapi
