// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateCampaignReq create campaign req
//
// swagger:model CreateCampaignReq
type CreateCampaignReq struct {

	// account
	Account string `json:"account,omitempty"`

	// ad rotation
	AdRotation string `json:"adRotation,omitempty"`

	// ad schedule
	AdSchedule string `json:"adSchedule,omitempty"`

	// bid strategy name
	BidStrategyName string `json:"bidStrategyName,omitempty"`

	// bid strategy type
	BidStrategyType string `json:"bidStrategyType,omitempty"`

	// budget
	Budget float64 `json:"budget,omitempty"`

	// budget type
	BudgetType string `json:"budgetType,omitempty"`

	// campaign
	Campaign string `json:"campaign,omitempty"`

	// campaign type
	CampaignType string `json:"campaignType,omitempty"`

	// delivery method
	DeliveryMethod string `json:"deliveryMethod,omitempty"`

	// dsa language
	DsaLanguage string `json:"dsaLanguage,omitempty"`

	// dsa page feeds
	DsaPageFeeds string `json:"dsaPageFeeds,omitempty"`

	// dsa targeting source
	DsaTargetingSource string `json:"dsaTargetingSource,omitempty"`

	// dsa website
	DsaWebsite string `json:"dsaWebsite,omitempty"`

	// end date
	EndDate string `json:"endDate,omitempty"`

	// exclusion method
	ExclusionMethod string `json:"exclusionMethod,omitempty"`

	// flexible reach
	FlexibleReach string `json:"flexibleReach,omitempty"`

	// folder ID
	FolderID int64 `json:"folderID,omitempty"`

	// inventory type
	InventoryType string `json:"inventoryType,omitempty"`

	// languages
	Languages string `json:"languages,omitempty"`

	// location
	Location string `json:"location,omitempty"`

	// max c p c
	MaxCPC float64 `json:"maxCPC,omitempty"`

	// max c p m
	MaxCPM float64 `json:"maxCPM,omitempty"`

	// max c p v
	MaxCPV float64 `json:"maxCPV,omitempty"`

	// networks
	Networks string `json:"networks,omitempty"`

	// start date
	StartDate string `json:"startDate,omitempty"`

	// target c p a
	TargetCPA string `json:"targetCPA,omitempty"`

	// target c p m
	TargetCPM float64 `json:"targetCPM,omitempty"`

	// targeting method
	TargetingMethod string `json:"targetingMethod,omitempty"`
}

// Validate validates this create campaign req
func (m *CreateCampaignReq) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateCampaignReq) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateCampaignReq) UnmarshalBinary(b []byte) error {
	var res CreateCampaignReq
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
