// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateAdReq create ad req
//
// swagger:model CreateAdReq
type CreateAdReq struct {

	// data
	Data *CreateAdReqData `json:"data,omitempty"`
}

// Validate validates this create ad req
func (m *CreateAdReq) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateAdReq) validateData(formats strfmt.Registry) error {

	if swag.IsZero(m.Data) { // not required
		return nil
	}

	if m.Data != nil {
		if err := m.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CreateAdReq) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateAdReq) UnmarshalBinary(b []byte) error {
	var res CreateAdReq
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// CreateAdReqData create ad req data
//
// swagger:model CreateAdReqData
type CreateAdReqData struct {

	// ad group Id
	AdGroupID int64 `json:"adGroupId,omitempty"`

	// ad group status
	AdGroupStatus string `json:"adGroupStatus,omitempty"`

	// ad name
	AdName string `json:"adName,omitempty"`

	// approval status
	ApprovalStatus string `json:"approvalStatus,omitempty"`

	// bumper ad
	BumperAd string `json:"bumperAd,omitempty"`

	// campaign status
	CampaignStatus string `json:"campaignStatus,omitempty"`

	// comment
	Comment string `json:"comment,omitempty"`

	// display URL
	DisplayURL string `json:"displayURL,omitempty"`

	// final mobile Url
	FinalMobileURL string `json:"finalMobileUrl,omitempty"`

	// final Url
	FinalURL string `json:"finalUrl,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// video ID
	VideoID string `json:"videoID,omitempty"`
}

// Validate validates this create ad req data
func (m *CreateAdReqData) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateAdReqData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateAdReqData) UnmarshalBinary(b []byte) error {
	var res CreateAdReqData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
