// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateTechAdGroupResp create tech ad group resp
//
// swagger:model CreateTechAdGroupResp
type CreateTechAdGroupResp struct {

	// data
	Data *CreateTechAdGroupRespData `json:"data,omitempty"`
}

// Validate validates this create tech ad group resp
func (m *CreateTechAdGroupResp) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateTechAdGroupResp) validateData(formats strfmt.Registry) error {

	if swag.IsZero(m.Data) { // not required
		return nil
	}

	if m.Data != nil {
		if err := m.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CreateTechAdGroupResp) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateTechAdGroupResp) UnmarshalBinary(b []byte) error {
	var res CreateTechAdGroupResp
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// CreateTechAdGroupRespData create tech ad group resp data
//
// swagger:model CreateTechAdGroupRespData
type CreateTechAdGroupRespData struct {

	// ad group
	AdGroup string `json:"adGroup,omitempty"`

	// ad group type
	AdGroupType string `json:"adGroupType,omitempty"`

	// bid modifier
	BidModifier string `json:"bidModifier,omitempty"`

	// campaign ID
	CampaignID int64 `json:"campaignID,omitempty"`

	// content keywords
	ContentKeywords string `json:"contentKeywords,omitempty"`

	// criterion type
	CriterionType string `json:"criterionType,omitempty"`

	// custom bid type
	CustomBidType string `json:"customBidType,omitempty"`

	// custom parameters
	CustomParameters string `json:"customParameters,omitempty"`

	// desktop bid modifier
	DesktopBidModifier string `json:"desktopBidModifier,omitempty"`

	// destination URL
	DestinationURL string `json:"destinationURL,omitempty"`

	// display network
	DisplayNetwork string `json:"displayNetwork,omitempty"`

	// feed
	Feed string `json:"feed,omitempty"`

	// final URL suffix
	FinalURLSuffix string `json:"finalURLSuffix,omitempty"`

	// first page bid
	FirstPageBid string `json:"firstPageBid,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// max c p c
	MaxCPC float64 `json:"maxCPC,omitempty"`

	// max c p m
	MaxCPM float64 `json:"maxCPM,omitempty"`

	// max c p v
	MaxCPV float64 `json:"maxCPV,omitempty"`

	// mobile bid modifier
	MobileBidModifier string `json:"mobileBidModifier,omitempty"`

	// radius
	Radius string `json:"radius,omitempty"`

	// reach
	Reach string `json:"reach,omitempty"`

	// t v screen bid modifier
	TVScreenBidModifier string `json:"tVScreenBidModifier,omitempty"`

	// tablet bid modifier
	TabletBidModifier string `json:"tabletBidModifier,omitempty"`

	// target c p a
	TargetCPA string `json:"targetCPA,omitempty"`

	// target c p m
	TargetCPM float64 `json:"targetCPM,omitempty"`

	// target r o a s
	TargetROAS string `json:"targetROAS,omitempty"`

	// targeting optimization
	TargetingOptimization string `json:"targetingOptimization,omitempty"`

	// top content bid modifier
	TopContentBidModifier string `json:"topContentBidModifier,omitempty"`

	// top of page bid
	TopOfPageBid string `json:"topOfPageBid,omitempty"`

	// tracking template
	TrackingTemplate string `json:"trackingTemplate,omitempty"`

	// unit
	Unit string `json:"unit,omitempty"`
}

// Validate validates this create tech ad group resp data
func (m *CreateTechAdGroupRespData) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateTechAdGroupRespData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateTechAdGroupRespData) UnmarshalBinary(b []byte) error {
	var res CreateTechAdGroupRespData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
