// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateFolderReq create folder req
//
// swagger:model CreateFolderReq
type CreateFolderReq struct {

	// b l s split
	BLSSplit bool `json:"BLSSplit,omitempty"`

	// frequency
	Frequency string `json:"frequency,omitempty"`

	// name
	// Max Length: 255
	// Min Length: 1
	Name string `json:"name,omitempty"`

	// rules mask
	// Max Length: 15
	// Min Length: 12
	RulesMask string `json:"rulesMask,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this create folder req
func (m *CreateFolderReq) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRulesMask(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateFolderReq) validateName(formats strfmt.Registry) error {

	if swag.IsZero(m.Name) { // not required
		return nil
	}

	if err := validate.MinLength("name", "body", string(m.Name), 1); err != nil {
		return err
	}

	if err := validate.MaxLength("name", "body", string(m.Name), 255); err != nil {
		return err
	}

	return nil
}

func (m *CreateFolderReq) validateRulesMask(formats strfmt.Registry) error {

	if swag.IsZero(m.RulesMask) { // not required
		return nil
	}

	if err := validate.MinLength("rulesMask", "body", string(m.RulesMask), 12); err != nil {
		return err
	}

	if err := validate.MaxLength("rulesMask", "body", string(m.RulesMask), 15); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CreateFolderReq) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateFolderReq) UnmarshalBinary(b []byte) error {
	var res CreateFolderReq
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
