// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateAdGroupReq create ad group req
//
// swagger:model CreateAdGroupReq
type CreateAdGroupReq []*CreateAdGroupReqItems0

// Validate validates this create ad group req
func (m CreateAdGroupReq) Validate(formats strfmt.Registry) error {
	var res []error

	for i := 0; i < len(m); i++ {
		if swag.IsZero(m[i]) { // not required
			continue
		}

		if m[i] != nil {
			if err := m[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName(strconv.Itoa(i))
				}
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// CreateAdGroupReqItems0 create ad group req items0
//
// swagger:model CreateAdGroupReqItems0
type CreateAdGroupReqItems0 struct {

	// ad group ID
	AdGroupID []string `json:"adGroupID"`

	// ad schedule
	AdSchedule []string `json:"adSchedule"`

	// age
	Age []string `json:"age"`

	// audience
	Audience []string `json:"audience"`

	// campaign ID
	CampaignID int64 `json:"campaignID,omitempty"`

	// channel ID
	ChannelID []string `json:"channelID"`

	// custom audience
	CustomAudience []string `json:"customAudience"`

	// devices
	Devices []string `json:"devices"`

	// folder ID
	FolderID int64 `json:"folderID,omitempty"`

	// frequency
	Frequency []string `json:"frequency"`

	// gender
	Gender []string `json:"gender"`

	// id
	ID int64 `json:"id,omitempty"`

	// interest
	Interest []string `json:"interest"`

	// keyword
	Keyword []string `json:"keyword"`

	// languages
	Languages []string `json:"languages"`

	// location
	Location []string `json:"location"`

	// placement
	Placement []string `json:"placement"`

	// tech ad group ID
	TechAdGroupID int64 `json:"techAdGroupID,omitempty"`

	// topics
	Topics []string `json:"topics"`
}

// Validate validates this create ad group req items0
func (m *CreateAdGroupReqItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateAdGroupReqItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateAdGroupReqItems0) UnmarshalBinary(b []byte) error {
	var res CreateAdGroupReqItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
