// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// ErrorMess error mess
//
// swagger:model ErrorMess
type ErrorMess string

// Validate validates this error mess
func (m ErrorMess) Validate(formats strfmt.Registry) error {
	return nil
}
