// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetAdResp get ad resp
//
// swagger:model GetAdResp
type GetAdResp struct {

	// data
	Data []*GetAdRespDataItems0 `json:"data"`
}

// Validate validates this get ad resp
func (m *GetAdResp) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetAdResp) validateData(formats strfmt.Registry) error {

	if swag.IsZero(m.Data) { // not required
		return nil
	}

	for i := 0; i < len(m.Data); i++ {
		if swag.IsZero(m.Data[i]) { // not required
			continue
		}

		if m.Data[i] != nil {
			if err := m.Data[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetAdResp) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetAdResp) UnmarshalBinary(b []byte) error {
	var res GetAdResp
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// GetAdRespDataItems0 get ad resp data items0
//
// swagger:model GetAdRespDataItems0
type GetAdRespDataItems0 struct {

	// ad group Id
	AdGroupID int64 `json:"adGroupId,omitempty"`

	// ad group status
	AdGroupStatus string `json:"adGroupStatus,omitempty"`

	// ad name
	AdName string `json:"adName,omitempty"`

	// approval status
	ApprovalStatus string `json:"approvalStatus,omitempty"`

	// bumper ad
	BumperAd string `json:"bumperAd,omitempty"`

	// campaign status
	CampaignStatus string `json:"campaignStatus,omitempty"`

	// comment
	Comment string `json:"comment,omitempty"`

	// display URL
	DisplayURL string `json:"displayURL,omitempty"`

	// final mobile Url
	FinalMobileURL string `json:"finalMobileUrl,omitempty"`

	// final Url
	FinalURL string `json:"finalUrl,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// video ID
	VideoID string `json:"videoID,omitempty"`
}

// Validate validates this get ad resp data items0
func (m *GetAdRespDataItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetAdRespDataItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetAdRespDataItems0) UnmarshalBinary(b []byte) error {
	var res GetAdRespDataItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
