// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetFoldersResp get folders resp
//
// swagger:model GetFoldersResp
type GetFoldersResp struct {

	// data
	Data []*GetFoldersRespDataItems0 `json:"data"`
}

// Validate validates this get folders resp
func (m *GetFoldersResp) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetFoldersResp) validateData(formats strfmt.Registry) error {

	if swag.IsZero(m.Data) { // not required
		return nil
	}

	for i := 0; i < len(m.Data); i++ {
		if swag.IsZero(m.Data[i]) { // not required
			continue
		}

		if m.Data[i] != nil {
			if err := m.Data[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetFoldersResp) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetFoldersResp) UnmarshalBinary(b []byte) error {
	var res GetFoldersResp
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// GetFoldersRespDataItems0 get folders resp data items0
//
// swagger:model GetFoldersRespDataItems0
type GetFoldersRespDataItems0 struct {

	// b l s split
	BLSSplit bool `json:"BLSSplit,omitempty"`

	// created at
	CreatedAt string `json:"createdAt,omitempty"`

	// frequency
	Frequency string `json:"frequency,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// rules mask
	RulesMask string `json:"rulesMask,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this get folders resp data items0
func (m *GetFoldersRespDataItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetFoldersRespDataItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetFoldersRespDataItems0) UnmarshalBinary(b []byte) error {
	var res GetFoldersRespDataItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
