// Code generated by go-swagger; DO NOT EDIT.

package models

import "io"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// GetFileResp get file resp
//
// swagger:model GetFileResp
type GetFileResp io.ReadCloser
