// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ListVideosResp list videos resp
//
// swagger:model ListVideosResp
type ListVideosResp []*ListVideosRespItems0

// Validate validates this list videos resp
func (m ListVideosResp) Validate(formats strfmt.Registry) error {
	var res []error

	for i := 0; i < len(m); i++ {
		if swag.IsZero(m[i]) { // not required
			continue
		}

		if m[i] != nil {
			if err := m[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName(strconv.Itoa(i))
				}
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ListVideosRespItems0 list videos resp items0
//
// swagger:model ListVideosRespItems0
type ListVideosRespItems0 struct {

	// adgroup ID
	AdgroupID int64 `json:"adgroupID,omitempty"`

	// creative ID
	CreativeID string `json:"creativeID,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// folder ID
	FolderID int64 `json:"folderID,omitempty"`

	// title
	Title string `json:"title,omitempty"`

	// youtube ID
	YoutubeID string `json:"youtubeID,omitempty"`
}

// Validate validates this list videos resp items0
func (m *ListVideosRespItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ListVideosRespItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ListVideosRespItems0) UnmarshalBinary(b []byte) error {
	var res ListVideosRespItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
