// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MatchFoldersReq match folders req
//
// swagger:model MatchFoldersReq
type MatchFoldersReq struct {

	// audience folder ID
	AudienceFolderID int64 `json:"audienceFolderID,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// video folder ID
	VideoFolderID int64 `json:"videoFolderID,omitempty"`
}

// Validate validates this match folders req
func (m *MatchFoldersReq) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MatchFoldersReq) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MatchFoldersReq) UnmarshalBinary(b []byte) error {
	var res MatchFoldersReq
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
