// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MatchFoldersResp match folders resp
//
// swagger:model MatchFoldersResp
type MatchFoldersResp struct {

	// data
	Data *MatchFoldersRespData `json:"data,omitempty"`
}

// Validate validates this match folders resp
func (m *MatchFoldersResp) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MatchFoldersResp) validateData(formats strfmt.Registry) error {

	if swag.IsZero(m.Data) { // not required
		return nil
	}

	if m.Data != nil {
		if err := m.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *MatchFoldersResp) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MatchFoldersResp) UnmarshalBinary(b []byte) error {
	var res MatchFoldersResp
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// MatchFoldersRespData match folders resp data
//
// swagger:model MatchFoldersRespData
type MatchFoldersRespData struct {

	// audience folder ID
	AudienceFolderID int64 `json:"audienceFolderID,omitempty"`

	// audience folder name
	AudienceFolderName string `json:"audienceFolderName,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// video folder ID
	VideoFolderID int64 `json:"videoFolderID,omitempty"`

	// video folder name
	VideoFolderName string `json:"videoFolderName,omitempty"`
}

// Validate validates this match folders resp data
func (m *MatchFoldersRespData) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MatchFoldersRespData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MatchFoldersRespData) UnmarshalBinary(b []byte) error {
	var res MatchFoldersRespData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
